### PR TITLE
@R add support for m68k-*-amiga

### PR DESCRIPTION
**Pull request by bebbo**
These changes are re-adding the support for the Amiga with Motorola 68*** cpus.

### CODE REVIEW

**Comment by jwakely** [comment]
This is an unofficial, read-only mirror.

**Comment by AraHaan** [comment]
Hmm what if I use the same mentionbot concept that the Python Software Foundation use on github pull requests that would automatically redirect github pull request patches to the correct place in case the person submitting has no way to send plain text emails weather or not they use Microsoft Windows and if they only have yahoo and / or gmail emails that only send emails in HTML form even if they do not want to. Which then excludes all Windows users or phone users from being able to request gcc patches.

Hope you guys understand that not everyone can send plain text emails even if they wanted to making them unable to submit gcc issues or patches. Not only that but for them it would then mean they would have to try github or freenode to report them in their case.

**Comment by jwakely** [comment]
If you can't send a simple email how are you going to manage to test patches to the compiler?

Bugs should be reported to https://gcc.gnu.org/bugs/ not here or IRC.

**Comment by AraHaan** [comment]
oh, Well I use cygwin64/mingw64 to test patches.

**Pull request closed without merging**
